future: true
# Dependencies
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               guruchun's memory
url:                 http://guruchun.github.io
paginate:            5


#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Steve Chun (천해철)
emal: guruchun@gmail.com

# Short bio or description (displayed in the header)
description: System & Software Engineer working for LG CNS


theme: jekyll-theme-slate
